'use client';
import { ExternalLink, ArrowLeft, Link2, Sparkles, Heart } from 'lucide-react'; import Image from 'next/image'; import Link from 'next/link';
export default function LinksPage() {
  const friend = {n:'GitHub',u:'https://github.com/SanshuiBot',a:'/sanshui-blog/github.png',d:'个人开源项目托管平台'};
  return (<div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-24"><Link href="/" className="inline-flex items-center gap-1.5 text-sm text-stone-500 hover:text-stone-900 dark:hover:text-stone-200 transition-colors mb-8 group/back"><ArrowLeft size={16} className="transition-transform group/back:-translate-x-1"/>返回首页</Link>
  <div className="mb-12"><span className="inline-flex items-center gap-1.5 text-xs font-medium text-fuchsia-600 dark:text-fuchsia-400 uppercase tracking-widest mb-4"><Link2 size={12}/>友链</span><h1 className="text-4xl sm:text-5xl font-bold text-stone-900 dark:text-stone-50 tracking-tight"><span className="holo-text">友情链接</span></h1><p className="mt-3 text-stone-500 dark:text-stone-400">那些人，那些事</p></div>
  <a key={friend.n} href={friend.u} target="_blank" rel="noopener noreferrer" className="group relative flex items-center gap-5 p-6 rounded-2xl bg-white/80 dark:bg-stone-900/80 backdrop-blur border border-stone-200/60 dark:border-stone-800/60 hover:border-transparent transition-all duration-700 hover:shadow-[0_0_30px_rgba(244,114,182,0.15)]">
    <div className="w-14 h-14 rounded-2xl overflow-hidden flex-shrink-0 bg-stone-100 dark:bg-stone-800 ring-2 ring-stone-200/50 dark:ring-stone-700/50 group-hover:ring-fuchsia-500/30 transition-all"><Image src={friend.a} alt={friend.n} width={56} height={56} className="w-full h-full object-cover" unoptimized/></div>
    <div className="flex-1 min-w-0"><div className="flex items-center gap-2"><span className="font-semibold text-stone-900 dark:text-stone-50 group-hover:holo-text transition-all truncate">{friend.n}</span><ExternalLink size={14} className="text-stone-400 opacity-0 group-hover:opacity-100 transition-all group-hover:translate-x-0.5"/></div><p className="text-sm text-stone-500 dark:text-stone-500 truncate">{friend.d}</p></div>
  </a>
  <div className="mt-12 p-8 rounded-3xl border border-stone-200/60 dark:border-stone-800/60 hover:shadow-[0_0_30px_rgba(244,114,182,0.1)] transition-all duration-700"><h2 className="text-xl font-bold text-stone-900 dark:text-stone-50 mb-3">想交换友链？</h2><p className="text-stone-600 dark:text-stone-400 mb-5">欢迎在 GitHub 仓库提 Issue 或发邮件给我.</p><div className="flex flex-wrap gap-3"><a href="mailto:localhost6@foxmail.com" className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-stone-900 dark:bg-stone-50 text-white dark:text-stone-900 text-sm font-medium hover:scale-105 active:scale-95 transition-transform"><Sparkles size={14}/>联系我</a><a href="https://github.com/SanshuiBot" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white dark:bg-stone-900 text-stone-700 dark:text-stone-300 text-sm font-medium border border-stone-200 dark:border-stone-800 hover:scale-105 active:scale-95 transition-transform hover:border-fuchsia-300 dark:hover:border-fuchsia-700"><Heart size={14} className="text-fuchsia-500"/>GitHub</a></div></div>
</div>);}
