'use client';
import { useState, useEffect, useRef, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Search as LucideSearch, X, ArrowRight } from 'lucide-react';
import Link from 'next/link';
export default function Search({ posts }: { posts: any[] }) {
  const [open, setOpen] = useState(false); const [q, setQ] = useState(''); const ref = useRef<HTMLInputElement>(null);
  const r = useMemo(() => {const t=q.trim().toLowerCase();if(!t)return[];return posts.filter(p=>p.title.toLowerCase().includes(t)||p.excerpt.toLowerCase().includes(t)||p.tags.some((x:string)=>x.toLowerCase().includes(t))).slice(0,8);},[q,posts]);
  useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setOpen(true);}if(e.key==='Escape')setOpen(false);};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h);},[]);
  useEffect(()=>{if(open)setTimeout(()=>ref.current?.focus(),100);},[open]);
  const fmt=(d:string)=>new Date(d).toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'});
  return(<><button onClick={()=>setOpen(true)} className="p-3 rounded-full glass-s text-stone-500 dark:text-stone-400 hover:text-stone-900 dark:hover:text-stone-200 shadow-lg active:scale-95 transition-all" aria-label="搜索"><LucideSearch size={16}/></button>
  <AnimatePresence>{open&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[70] flex items-start justify-center pt-[15vh] px-4"><motion.div className="fixed inset-0 bg-black/40 backdrop-blur-sm" onClick={()=>setOpen(false)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/>
  <motion.div initial={{opacity:0,scale:.95,y:-20}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:.95,y:-20}} className="relative w-full max-w-xl bg-white dark:bg-stone-900 rounded-3xl shadow-2xl border border-stone-200 dark:border-stone-800 overflow-hidden">
  <div className="absolute top-0 inset-x-0 h-px overflow-hidden"><motion.div className="h-full" style={{background:'linear-gradient(90deg,transparent,#f472b6,#c084fc,#60a5fa,#34d399,transparent)',backgroundSize:'200% 100%'}} animate={{backgroundPosition:['0%','200%']}} transition={{duration:3,repeat:Infinity,ease:'linear'}}/></div>
  <div className="flex items-center gap-3 px-5 py-4 border-b border-stone-200 dark:border-stone-800"><LucideSearch size={18} className="text-stone-400 shrink-0"/><input ref={ref} type="text" value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索文章..." className="flex-1 bg-transparent text-stone-900 dark:text-stone-50 placeholder-stone-400 outline-none text-base"/>{q&&<button onClick={()=>setQ('')} className="text-stone-400 hover:text-stone-600"><X size={16}/></button>}<kbd className="hidden sm:inline-flex px-1.5 py-0.5 rounded text-[10px] font-mono bg-stone-200 dark:bg-stone-700 text-stone-500">ESC</kbd></div>
  <div className="max-h-80 overflow-y-auto p-2">{r.length>0?<div className="space-y-0.5">{r.map((p,i)=><motion.div key={p.slug} initial={{opacity:0,x:-10}} animate={{opacity:1,x:0}} transition={{delay:i*.03}}><Link href={`/posts/${p.slug}`} onClick={()=>setOpen(false)} className="flex items-center gap-3 px-3 py-3 rounded-xl hover:bg-stone-100 dark:hover:bg-stone-800 transition-colors group"><div className="flex-1 min-w-0"><span className="font-medium text-stone-900 dark:text-stone-50 group-hover:text-fuchsia-600 dark:group-hover:text-fuchsia-400 transition-colors truncate block">{p.title}</span><span className="text-xs text-stone-400">{fmt(p.date)}</span></div><ArrowRight size={14} className="text-stone-300 dark:text-stone-600 group-hover:text-violet-500 shrink-0"/></Link></motion.div>)}</div>:q?<div className="text-center py-10 text-stone-500 text-sm">未找到相关文章</div>:<div className="text-center py-10 text-stone-400 dark:text-stone-600 text-sm">⌘K 搜索</div>}</div></motion.div></motion.div>}</AnimatePresence></>);
}
